// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORM;

#nullable disable

namespace ORM.Migrations
{
    [DbContext(typeof(DbManager))]
    partial class DbManagerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Models.SleepEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("bed_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DreamMood")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dream_mood");

                    b.Property<string>("DreamText")
                        .HasColumnType("longtext")
                        .HasColumnName("dream_text");

                    b.Property<string>("FallAsleepDurationCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fall_asleep_duration_category");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<int>("SleepQuality")
                        .HasColumnType("int")
                        .HasColumnName("sleep_quality");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WakeTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("wake_time");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BedTime");

                    b.ToTable("sleep_entries");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("activity_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("DailyWaterGoalMl")
                        .HasColumnType("int")
                        .HasColumnName("daily_water_goal_ml");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<bool>("ReminderEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("reminder_enabled");

                    b.Property<int>("ReminderEndHour")
                        .HasColumnType("int")
                        .HasColumnName("reminder_end_hour");

                    b.Property<int>("ReminderIntervalMinutes")
                        .HasColumnType("int")
                        .HasColumnName("reminder_interval_minutes");

                    b.Property<int>("ReminderStartHour")
                        .HasColumnType("int")
                        .HasColumnName("reminder_start_hour");

                    b.Property<bool>("SleepReminderEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sleep_reminder_enabled");

                    b.Property<int>("TargetBedTimeHour")
                        .HasColumnType("int")
                        .HasColumnName("target_bed_time_hour");

                    b.Property<int>("TargetBedTimeMinute")
                        .HasColumnType("int")
                        .HasColumnName("target_bed_time_minute");

                    b.Property<double>("TargetSleepHours")
                        .HasColumnType("double")
                        .HasColumnName("target_sleep_hours");

                    b.Property<int>("TargetWakeTimeHour")
                        .HasColumnType("int")
                        .HasColumnName("target_wake_time_hour");

                    b.Property<int>("TargetWakeTimeMinute")
                        .HasColumnType("int")
                        .HasColumnName("target_wake_time_minute");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.Property<double?>("WeekendTargetSleepHours")
                        .HasColumnType("double")
                        .HasColumnName("weekend_target_sleep_hours");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Models.WaterEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountMl")
                        .HasColumnType("int")
                        .HasColumnName("amount_ml");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("logged_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LoggedAt");

                    b.ToTable("water_entries");
                });

            modelBuilder.Entity("Models.SleepEntry", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithMany("SleepEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.WaterEntry", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithMany("WaterEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Navigation("SleepEntries");

                    b.Navigation("WaterEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
